### ISSUE TITLE
log operation in Calculator.py

### ISSUE THREAD

**Issue by ajayjha5899** [aditeyabaral/GPython#4]
log operation is not written correctly. I think there's some undefined 'log' variable which is causing this issue.

**Comment by BassCoder2808** [comment]
I would like to work on this issue
Can you please assign it to me ?

**Comment by aditeyabaral** [comment]
Sure, go ahead 👍

**Comment by BassCoder2808** [comment]
Thanks!.
I have created the pull request for this issue.
